### ISSUE TITLE
Invalid type 1002

### ISSUE THREAD

**Issue by j2l** [gd-com/examples#1]
Hello, bonjour
Very nice project. I really hope to see it rise!
I tested both simple and advanced websocket examples and had trouble with both on glitch.com
Here's my setup, it might help others too.

In the advanced godot project, I set:
`var url = "ws://godot-websocket.glitch.me"`
and copied server files to glitch: https://glitch.com/edit/#!/godot-websocket

Running client and server, connection works:
```
** Debug Process Started **
OpenGL ES 3.0 Renderer: GeForce GTX 970/PCIe/SSE2
Connecting to ws://godot-websocket.glitch.me
Connection Established With Protocol: default
```
But as soon as I click the right arrow key, I have:
client:
`Recieve 0` (the Math.random())
server:
```
connected

Promise { <pending> }

(node:1628) UnhandledPromiseRejectionWarning: Error: Decode buffer error: Invalid type 1002

    at decode (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/@gd-com/utils/2.3.0/node_modules/@gd-com/utils/src/get/get_var/index.js:33:11)

    at module.exports (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/@gd-com/utils/2.3.0/node_modules/@gd-com/utils/src/get/get_var/index.js:39:27)

    at GdBuffer._internalGet (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/@gd-com/utils/2.3.0/node_modules/@gd-com/utils/src/buffer/GdBuffer.js:10:24)

    at GdBuffer.getVar (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/@gd-com/utils/2.3.0/node_modules/@gd-com/utils/src/buffer/GdBuffer.js:72:17)

at WebSocket.ws.on (/app/server.js:12:25)

```

Do you have an idea?
BTW, I can't make it work with wss (443) on glitch, might need something else at some point.

**Comment by Tilican** [comment]
Hi,
Thx for your report.
I'll tcheck that tomorow

**Comment by Tilican** [comment]
Hi @j2l ,

Carreful you project use an old version of `@gd-com/utils`, now in `4.0.0`  there is no more promises !

Take a look at : https://glitch.com/edit/#!/gd-com-ws-basic, it woks.
For https you need to set ssl on godot, i never try that sorry...

**Comment by j2l** [comment]
Sorry, didn't see your message.
I thought glitch was checking the package against npmjs, but it looks like it's not. Good to know!

Well, clicking on right arrow throws:
```
/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/@gd-com/utils/4.0.0/node_modules/@gd-com/utils/src/get/get_var/index.js:33

    throw new Error(`Decode buffer error: Invalid type ${type}`)

    ^


Error: Decode buffer error: Invalid type 1002

    at decode (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/@gd-com/utils/4.0.0/node_modules/@gd-com/utils/src/get/get_var/index.js:33:11)

    at module.exports (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/@gd-com/utils/4.0.0/node_modules/@gd-com/utils/src/get/get_var/index.js:40:16)

    at GdBuffer._internalGet (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/@gd-com/utils/4.0.0/node_modules/@gd-com/utils/src/buffer/GdBuffer.js:10:18)

    at GdBuffer.getVar (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/@gd-com/utils/4.0.0/node_modules/@gd-com/utils/src/buffer/GdBuffer.js:72:17)

at WebSocket.ws.on (/app/server.js:14:25)

    at WebSocket.emit (events.js:182:13)

    at Receiver.receiverOnMessage (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/ws/5.2.2/node_modules/ws/lib/websocket.js:720:20)

    at Receiver.emit (events.js:182:13)

    at Receiver.dataMessage (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/ws/5.2.2/node_modules/ws/lib/receiver.js:405:14)

    at Receiver.getData (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/ws/5.2.2/node_modules/ws/lib/receiver.js:346:17)
```

and on the left arrow:
```
connected

internal/buffer.js:53

  throw new ERR_OUT_OF_RANGE(type || 'offset',

  ^


RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 0. Received 2

    at boundsError (internal/buffer.js:53:9)

    at Buffer.readInt16LE (internal/buffer.js:299:5)

    at decode (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/@gd-com/utils/4.0.0/node_modules/@gd-com/utils/src/get/get_var/index.js:29:23)

    at module.exports (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/@gd-com/utils/4.0.0/node_modules/@gd-com/utils/src/get/get_var/index.js:40:16)

    at GdBuffer._internalGet (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/@gd-com/utils/4.0.0/node_modules/@gd-com/utils/src/buffer/GdBuffer.js:10:18)

    at GdBuffer.getVar (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/@gd-com/utils/4.0.0/node_modules/@gd-com/utils/src/buffer/GdBuffer.js:72:17)

at WebSocket.ws.on (/app/server.js:14:25)

    at WebSocket.emit (events.js:182:13)

    at Receiver.receiverOnMessage (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/ws/5.2.2/node_modules/ws/lib/websocket.js:720:20)

    at Receiver.emit (events.js:182:13)
```

I also tried with your glitch server, If it works fine for you I guess the problem is in my client.
I use stock Godot 3.1 on Win10Pro

**Comment by Tilican** [comment]
Hum, i only tcheck the basic example !
I'll tcheck advanced example later

**Comment by j2l** [comment]
Thanks
As explained, your basic server is not working for me too

**Comment by Tilican** [comment]
Server advanced 
- source code : https://glitch.com/~gd-com-ws-advanced
- server url : ws://gd-com-ws-advanced.glitch.me/

Server basic 
- source code : https://glitch.com/~gd-com-ws-basic
- server url : ws://gd-com-ws-basic.glitch.me/

Everything is working for me with basic and advanced example from the repo

**Comment by Tilican** [comment]
As i see in your message, you try to use an advanced client with a basic server :warning: 

> Sorry, didn't see your message.
> I thought glitch was checking the package against npmjs, but it looks like it's not. Good to know!
> 
> Well, clicking on right arrow throws:
> 
> ```
> /rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/@gd-com/utils/4.0.0/node_modules/@gd-com/utils/src/get/get_var/index.js:33
> 
>     throw new Error(`Decode buffer error: Invalid type ${type}`)
> 
>     ^
> 
> 
> Error: Decode buffer error: Invalid type 1002
> 
>     at decode (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/@gd-com/utils/4.0.0/node_modules/@gd-com/utils/src/get/get_var/index.js:33:11)
> 
>     at module.exports (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/@gd-com/utils/4.0.0/node_modules/@gd-com/utils/src/get/get_var/index.js:40:16)
> 
>     at GdBuffer._internalGet (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/@gd-com/utils/4.0.0/node_modules/@gd-com/utils/src/buffer/GdBuffer.js:10:18)
> 
>     at GdBuffer.getVar (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/@gd-com/utils/4.0.0/node_modules/@gd-com/utils/src/buffer/GdBuffer.js:72:17)
> 
> at WebSocket.ws.on (/app/server.js:14:25)
> 
>     at WebSocket.emit (events.js:182:13)
> 
>     at Receiver.receiverOnMessage (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/ws/5.2.2/node_modules/ws/lib/websocket.js:720:20)
> 
>     at Receiver.emit (events.js:182:13)
> 
>     at Receiver.dataMessage (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/ws/5.2.2/node_modules/ws/lib/receiver.js:405:14)
> 
>     at Receiver.getData (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/ws/5.2.2/node_modules/ws/lib/receiver.js:346:17)
> ```
> and on the left arrow:
> 
> ```
> connected
> 
> internal/buffer.js:53
> 
>   throw new ERR_OUT_OF_RANGE(type || 'offset',
> 
>   ^
> 
> 
> RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 0. Received 2
> 
>     at boundsError (internal/buffer.js:53:9)
> 
>     at Buffer.readInt16LE (internal/buffer.js:299:5)
> 
>     at decode (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/@gd-com/utils/4.0.0/node_modules/@gd-com/utils/src/get/get_var/index.js:29:23)
> 
>     at module.exports (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/@gd-com/utils/4.0.0/node_modules/@gd-com/utils/src/get/get_var/index.js:40:16)
> 
>     at GdBuffer._internalGet (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/@gd-com/utils/4.0.0/node_modules/@gd-com/utils/src/buffer/GdBuffer.js:10:18)
> 
>     at GdBuffer.getVar (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/@gd-com/utils/4.0.0/node_modules/@gd-com/utils/src/buffer/GdBuffer.js:72:17)
> 
> at WebSocket.ws.on (/app/server.js:14:25)
> 
>     at WebSocket.emit (events.js:182:13)
> 
>     at Receiver.receiverOnMessage (/rbd/pnpm-volume/8828148e-38bb-4dad-aab3-93f2cac614ea/node_modules/.registry.npmjs.org/ws/5.2.2/node_modules/ws/lib/websocket.js:720:20)
> 
>     at Receiver.emit (events.js:182:13)
> ```
> I also tried with your glitch server, If it works fine for you I guess the problem is in my client.
> I use stock Godot 3.1 on Win10Pro

**Comment by j2l** [comment]
@Tilican 
Sorry was on vacation (yeh!)
I guess you're right. Basic is working now.
[Advanced ](https://glitch.com/~gd-com-ws-advanced) has a glitch on glitch:
```
 failed to start application on gd-com-ws-advanced.glitch.me

  This is most likely because your project has a code error.
  Check your project logs, fix the error and try again. 
```

**Comment by Tilican** [comment]
Hi,
You have to change variable name from process to another thing ! :)
